### ISSUE TITLE
Your code is brokeded?

### ISSUE THREAD

**Issue by spectraldev** [PeterFred/hello-world#2]
I am a simple user and I found an error thingy. What do? How to fix? @PeterFred Halllp.

_Just checking you can mark an issue as resolved_

**Comment by PeterFred** [comment]
What is the error and i'll look to correct?

**Comment by PeterFred** [comment]
Or if just a test I can mark as resolved?

**Comment by spectraldev** [comment]
Just a test - Nice work. You can mark this as resolved

**Comment by PeterFred** [comment]
Fixed!
